articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('<slug>/', views.article_detail, name="detail"),
]

financialanalyticsbotswana/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about, name='about'),
    path('', views.homepage, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from . import views

app_name = 'market'

urlpatterns = [
    path('', views.chart, name="chart"),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=False)

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['date']

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100] + '...'

articles/views.py
from django.shortcuts import render
from .models import Article
from django.contrib.auth.decorators import login_required


@login_required(login_url="/accounts/login")
def article_list(request):
    articles = Article.objects.all().order_by('-date')
    return render(request, 'articles/article_list.html', {'articles': articles})


@login_required(login_url="/accounts/login")
def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block title %}
    FAB | Article Detail
{% endblock %}

{% block content %}
   <div class="container">
    <div>
        <h2>{{ article.title }}</h2>
        <p>{{ article.date }}</p>
        <img class="responsive-img" src="{{ article.thumb.url }}">
        <p>{{ article.body }}</p>
    </div>
   </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block title %}
    FAB | Article List
{% endblock %}

{% block content %}

    <!-- Page title and tags starts -->
    <div class="center-align" style="margin-bottom: 20px;">
    <h3 style="font-weight: bold;">Articles</h3>
    <h6 class="grey-text text-darken-2">
        "Finance is not merely about making money. It's about achieving our
        deep goals and protecting the fruits of our labor. It's about stewardship
        and, therefore, about achieving the good society." - Robert J. Shiller
    </h6>

    <!-- Tags -->
     <div style="margin-top: 20px;">
      <div class="chip">
        Finance
      </div>

      <div class="chip">
        Corporate
      </div>

      <div class="chip">
        Community
      </div>
    </div> <!-- Tags End hers-->

    </div>
    <!-- Page title and tags end here -->

    <div class="container">
            <div class="row">
                {%  for article in articles %}
                <div class="col s12 m4 ">
                    <div class="card hoverable">
                        <div class="card-image">
                            <img class="responsive-img materialboxed" src="{{ article.thumb.url }}">
                            <a href="{% url 'articles:detail' slug=article.slug %}"  class="btn-floating halfway-fab waves-effect waves-light coffee-pot"><i class="material-icons">book</i></a>
                        </div>
                        <div class="card-content">
                            <p class="grey-text">{{ article.date }}</p>
                            <h5 class="coffee-pot-text">{{ article.title }}</h5>
                            <span>{{ article.author }}</span>
                            <p>{{ article.snippet }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'articles:detail' slug=article.slug %}" class="deep-orange-text">Read More</a>
                         </div>
                    </div>
                </div>
                 {% endfor %}
            </div>
    </div>

{% endblock %}