accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name='logout')
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('<slug>/', views.article_detail, name="detail"),
]

financialanalyticsbotswana/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about, name='about'),
    path('', views.homepage, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from . import views

app_name = 'market'

urlpatterns = [
    path('', views.chart, name="chart"),
]

templates/about.html
{% extends 'base_layout.html' %}

{% block title %}
    FAB |  About
{% endblock %}

{% block content %}
    <p>Its about you not me</p>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
             {% block title %}
             {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        {% block fusion_chart_lib %}
        {% endblock %}
    </head>
    <body class="cream">
        <!-- start of header -->
        <header class="header">
            <!--Navbar content-->
            <nav class="cognac">
                <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <div class="nav-wrapper container">
                  <a href="{% url 'home' %}" class="brand-logo">FAB</a>
                  <ul id="nav-mobile" class="right hide-on-med-and-down">
                     <li><a href="{% url 'home' %}">Home</a></li>
                    {% if user.is_authenticated %}
                         <li><a href="{% url 'market:chart' %}">Market</a></li>
                         <li><a href="{% url 'articles:list' %}">Articles</a></li>
                    {% endif %}
                    <li><a href="{% url 'about' %}">About</a></li>
                         {% if user.is_authenticated %}
                           <li>
                               <form action="{% url 'accounts:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn-floating btn-small  waves-effect waves-light red accent-3" type="submit">
                                        <i class="material-icons">power_settings_new</i>
                                    </button>
                               </form>
                           </li>
                         {% else %}
                            <li>
                                <a href="{% url 'accounts:login' %}">
                                    <i class="material-icons">person_outline</i>
                                </a>
                            </li>
                         {% endif %}
                  </ul>
                </div>
            </nav>
            <!-- end of navbar content-->

            <!-- start of sidenav content -->
            <ul class="collection sidenav" id="slide-out">
                 <li><a href="{% url 'home' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'market:chart' %}">Market</a></li>
                    <li><a href="{% url 'articles:list' %}">Articles</a></li>
                {% endif %}
               <li><a href="{% url 'about' %}">About</a></li>
                   {% if user.is_authenticated %}
                           <li>
                               <a>
                                   <form action="{% url 'accounts:logout' %}" method="post">
                                        {% csrf_token %}
                                        <button class="btn-floating btn-small waves-effect waves-light red accent-3" type="submit">
                                            <i class="material-icons">power_settings_new</i>
                                        </button>
                                    </form>
                               </a>
                           </li>
                         {% else %}
                            <li>
                                <a href="{% url 'accounts:login' %}">
                                    <i class="material-icons">person_outline</i>
                                </a>
                            </li>
                   {% endif %}
             </ul>
            <!-- end of sidenav content -->
        </header>
        <!-- end of header -->

        <!-- Start of main content -->
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <!-- end of main content -->

         <!-- start of footer -->
        <footer class="page-footer cognac">
        <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Famous Quotes </h5>
                <p class="grey-text text-lighten-4">
                     <ol>
                        <li>"Wealth consists not in having great possessions, but in having few wants" - Epictettus</li>
                        <li>"The only way you will ever permanently take control of your financial ife is to dig deep and fix the root problem" - Suze Orman</li>
                        <li>"A budget tells us what we can't afford, but it doesn't keep us from buying it" - Wiliam Feather</li>
                    </ol>
                </p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="{% url 'home' %}"><i class="material-icons">home</i></a></li>
                    {% if user.is_authenticated %}
                         <li><a class="grey-text text-lighten-3" href="{% url 'market:chart' %}"><i class="material-icons">trending_up</i></a></li>
                         <li><a class="grey-text text-lighten-3" href="{% url 'articles:list' %}"><i class="material-icons">ballot</i></a></li>
                    {% endif %}
                    <li><a class="grey-text text-lighten-3" href="{% url 'about' %}"><i class="material-icons">info</i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2019 Copyright
            <a class="grey-text text-lighten-4 right" href="#!">We analyze for you</a>
            </div>
          </div>
        </footer>
        <!-- end of footer -->


        <div>
            <script src="{% static 'jquery/jquery.min.js' %}"></script>
            <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
            <script>
                 $(document).ready(function(){
                     $('.sidenav').sidenav();
                      {% block jquery %}
                      {% endblock %}
                 });
            </script>
        </div>
    </body>
</html>

templates/home.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}


{% block title %}
    FAB | Home
{% endblock %}

{% block content %}
     <!-- Section: Slider -->
  <section class="slider">
    <ul class="slides">
      <li>
        <img src="{% static 'img/home/slider01.jpg' %}" alt="">
        <div class="caption center-align">
          <h2>Plan for your financial freedom</h2>
          <h5 class="light grey-text text-lighten-3 hide-on-small-only">Live like a slave today so that tomorrow you may live like a king</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'img/home/slider02.jpg' %}" alt="">
        <div class="caption left-align">
          <h2>Money language</h2>
          <h5 class="light grey-text text-lighten-3 hide-on-small-only">Let the knowledge save you</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'img/home/slider02.jpg' %}" alt="">
        <div class="caption right-align">
          <h2>The is no change without sacrifice</h2>
          <h5 class="light grey-text text-lighten-3 hide-on-small-only">whats your dream?</h5>
        </div>
      </li>
    </ul>
  </section>
{% endblock %}
{% block jquery %}
    $('.slider').slider({
      indicators: false
    });
{% endblock %}

templates/homepage.html
{% extends 'base_layout.html' %}
{% block content %}
    <p>I am the homePage</p>
{% endblock %}ml>